In [2]:
import numpy as np

In [11]:
vec1 = np.array([[1,2,3],[2,3,4],[9,0,1]])
vec2 = np.array([[1,4,5],[2,3,4],[9,0,1]])

### it has two dimensions - rows and columns
### hence 2-D vectors (we can access using row indices and coloumn indices)

In [35]:
vec1.ndim

2

In [36]:
vec2.ndim

2

In [12]:
vec1

array([[1, 2, 3],
       [2, 3, 4],
       [9, 0, 1]])

In [13]:
vec2

array([[1, 4, 5],
       [2, 3, 4],
       [9, 0, 1]])

# dot product using numpy

In [15]:
# dot product

np.dot(vec1,vec2)

array([[32, 10, 16],
       [44, 17, 26],
       [18, 36, 46]])

# dot product using torch

In [16]:
import torch as torch

In [20]:
vec1_tensor = torch.tensor(vec1)
print(vec1)
print(vec1_tensor)

[[1 2 3]
 [2 3 4]
 [9 0 1]]
tensor([[1, 2, 3],
        [2, 3, 4],
        [9, 0, 1]])


In [22]:
vec2_tensor = torch.tensor(vec2)
print(vec2)
print(vec2_tensor)

[[1 4 5]
 [2 3 4]
 [9 0 1]]
tensor([[1, 4, 5],
        [2, 3, 4],
        [9, 0, 1]])


In [23]:
dot_product_torch = torch.dot(vec1_tensor,vec2_tensor)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [24]:
vec1_tensor.shape

torch.Size([3, 3])

# torch.dot function expects 1-D vectors

Our vector is 2-D,

we can use `torch.squeeze` to remove any extra dimensions


In [29]:
vec1_tensor = torch.squeeze(vec1_tensor)
print(vec1_tensor)
print(f'shape:{vec1_tensor.shape}')

tensor([[1, 2, 3],
        [2, 3, 4],
        [9, 0, 1]])
shape:torch.Size([3, 3])


In [30]:
vec2_tensor = torch.squeeze(vec2_tensor)
print(vec2_tensor)
print(f'shape:{vec2_tensor.shape}')

tensor([[1, 4, 5],
        [2, 3, 4],
        [9, 0, 1]])
shape:torch.Size([3, 3])


In [31]:
torch.dot(vec1_tensor,vec2_tensor)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

### It won't be resolved, because, our input matrix is itself 2-D

### Try matric multiplication for dot_product for 2-D

`torch.matmul()`

In [34]:
torch_dot_product = torch.matmul(vec1_tensor,vec2_tensor.T) # Transpose vec2_tensor to match dimensions
torch_dot_product

tensor([[24, 20, 12],
        [34, 29, 22],
        [14, 22, 82]])

# dot product using sentence_transformers.util.dot_score

In [42]:
from sentence_transformers import SentenceTransformer
from sentence_transformers import util

In [44]:
# load the model first

model = SentenceTransformer('all-mpnet-base-v2')

In [48]:
# get embeddings
embedding_1 = model.encode(vec1, convert_to_tensor=True)

TypeError: object of type 'numpy.int64' has no len()

# we cannot pass arrays
# we need to convert into strings / list of strings
# and then pass it into encode

In [55]:
vec1_to_list = vec1.tolist()
print(vec1_to_list)
vec2_to_list = vec2.tolist()
print(vec2_to_list)

[[1, 2, 3], [2, 3, 4], [9, 0, 1]]
[[1, 4, 5], [2, 3, 4], [9, 0, 1]]


In [85]:
embedding1 = model.encode(vec1_to_list)
print(f'data : {embedding1}')
print(f'shape : {embedding1.shape}')

data : [[ 0.05442027  0.03953015  0.00451795 ...  0.01809237 -0.09158307
  -0.0610432 ]
 [ 0.05589646 -0.02311823  0.00352699 ...  0.01853339 -0.10076108
  -0.03419292]
 [-0.05076252 -0.02119459  0.00390377 ...  0.01688002 -0.03411417
  -0.00084902]]
shape : (3, 768)


In [91]:
device = 'mps'
embedding1 = model.encode(vec1_to_list, convert_to_tensor=True).to(device)
print(f'data : {embedding1}')
print(f'shape : {embedding1.shape}')

data : tensor([[ 0.0544,  0.0395,  0.0045,  ...,  0.0181, -0.0916, -0.0610],
        [ 0.0559, -0.0231,  0.0035,  ...,  0.0185, -0.1008, -0.0342],
        [-0.0508, -0.0212,  0.0039,  ...,  0.0169, -0.0341, -0.0008]],
       device='mps:0')
shape : torch.Size([3, 768])


In [59]:
embedding2 = model.encode(vec2_to_list)
print(f'data : {embedding2}')
print(f'shape : {embedding2.shape}')

data : [[-0.02232088 -0.00593381 -0.01298535 ...  0.033519   -0.05398313
  -0.05386225]
 [ 0.05589646 -0.02311823  0.00352699 ...  0.01853339 -0.10076108
  -0.03419292]
 [-0.05076252 -0.02119459  0.00390377 ...  0.01688002 -0.03411417
  -0.00084902]]
shape : (3, 768)


In [92]:
embedding2 = model.encode(vec2_to_list,convert_to_tensor=True).to(device)
print(f'data : {embedding2}')
print(f'shape : {embedding2.shape}')

data : tensor([[-0.0223, -0.0059, -0.0130,  ...,  0.0335, -0.0540, -0.0539],
        [ 0.0559, -0.0231,  0.0035,  ...,  0.0185, -0.1008, -0.0342],
        [-0.0508, -0.0212,  0.0039,  ...,  0.0169, -0.0341, -0.0008]],
       device='mps:0')
shape : torch.Size([3, 768])


In [96]:
dot_product = util.dot_score(a=embedding1, b=embedding2)
dot_product

tensor([[0.7276, 0.8158, 0.4960],
        [0.7961, 1.0000, 0.5855],
        [0.6312, 0.5855, 1.0000]], device='mps:0')

In [98]:
torch.topk(dot_product, k=3)

torch.return_types.topk(
values=tensor([[0.8158, 0.7276, 0.4960],
        [1.0000, 0.7961, 0.5855],
        [1.0000, 0.6312, 0.5855]], device='mps:0'),
indices=tensor([[1, 0, 2],
        [1, 0, 2],
        [2, 0, 1]], device='mps:0'))

In [80]:
vec1_to_list[1]

[2, 3, 4]

In [81]:
vec2_to_list[1]

[2, 3, 4]

In [82]:
vec1_to_list[0]

[1, 2, 3]

In [83]:
vec2_to_list[0]

[1, 4, 5]

tensor([[1, 2, 3],
        [2, 3, 4],
        [9, 0, 1]])

# Cosine similarity




In [106]:


def dot_product(vector1,vector2):
    return torch.dot(vector1,vector2)


def cosine_similarity(vector1, vector2):
    dot_product = torch.dot(vector1,vector2)


    # Euclidean / L2 norm
    norm_vector1 = torch.sqrt(torch.sum(vector1**2))
    norm_vector2 = torch.sqrt(torch.sum(vector2**2))

    return dot_product / (norm_vector1 * norm_vector2)


# dot_product(torch.tensor(8,dtype=float32),torch.tensor(9,dtype=torch.float32))
# Example vectors / tensors

vector1 = torch.tensor([1,2,3], dtype=torch.float32)
vector2 = torch.tensor([1,2,3], dtype=torch.float32)
vector3 = torch.tensor([4,5,6], dtype=torch.float32)
vector4 = torch.tensor([-1,-5,-6], dtype=torch.float32)



# Calculate dot product and cosine similarity

In [109]:
print(f'dot product between vector1 - [1,2,3] and \n vector2 - [1,2,3] \n : {dot_product(vector1,vector2)}')
print(f'dot product between vector1 - [1,2,3] and \n vector3 - [4,5,6] \n : {dot_product(vector1,vector3)}')
print(f'dot product between vector1 - [1,2,3] and \n vector4 - [-1,-5,-6] \n : {dot_product(vector1,vector4)}')

dot product between vector1 - [1,2,3] and 
 vector2 - [1,2,3] 
 : 14.0
dot product between vector1 - [1,2,3] and 
 vector3 - [4,5,6] 
 : 32.0
dot product between vector1 - [1,2,3] and 
 vector4 - [-1,-5,-6] 
 : -29.0




Vector 1 and vector 2 should have the higher value. but dot product is not giving the exact result.

lets use `cosine similarity`

` we normalize by the magnitude `

In [110]:
print(f'cosine similarity between vector1 - [1,2,3] and \n vector2 - [1,2,3] \n : {cosine_similarity(vector1,vector2)}')
print(f'cosine similarity between vector1 - [1,2,3] and \n vector3 - [4,5,6] \n : {cosine_similarity(vector1,vector3)}')
print(f'cosine similarity between vector1 - [1,2,3] and \n vector4 - [-1,-5,-6] \n : {cosine_similarity(vector1,vector4)}')

cosine similarity between vector1 - [1,2,3] and 
 vector2 - [1,2,3] 
 : 0.9999999403953552
cosine similarity between vector1 - [1,2,3] and 
 vector3 - [4,5,6] 
 : 0.9746317863464355
cosine similarity between vector1 - [1,2,3] and 
 vector4 - [-1,-5,-6] 
 : -0.9843241572380066
